### ISSUE TITLE
like 模糊查询不生效

### ISSUE THREAD

**Issue by zm2911633440** [wuhuizuo/sqlm#3]
原：
![image](https://user-images.githubusercontent.com/59084616/120758983-11fada80-c545-11eb-92c4-934ef9217b2a.png)

改成这样就可以了：
![image](https://user-images.githubusercontent.com/59084616/120759072-2e971280-c545-11eb-9d15-e2865cfe694a.png)

**Comment by wuhuizuo** [comment]
fixed

```go
	format := fmt.Sprintf("%s like :%s", l.Key, l.Key)
	patterns := map[string]interface{}{l.Key: l.Value}
```

**Comment by wuhuizuo** [comment]
@zm2911633440
